services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - microservice
    networks:
      - app-network

  microservice:
    build: ./microservice
    ports:
      - "8000:8000"
    env_file:
      - ./microservice/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge